/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CucProgress: typeof import('./src/components/CucProgress/index.vue')['default']
    CusBtn: typeof import('./src/components/CusBtn/index.vue')['default']
    CusData: typeof import('./src/components/CusData/index.vue')['default']
    CusEmpty: typeof import('./src/components/CusEmpty/index.vue')['default']
    CusList: typeof import('./src/components/CusList/index.vue')['default']
    CusNav: typeof import('./src/components/CusNav/index.vue')['default']
    CusPicker: typeof import('./src/components/CusPicker/index.vue')['default']
    CusPop: typeof import('./src/components/CusPop/index.vue')['default']
    CusSelect: typeof import('./src/components/CusSelect/index.vue')['default']
    Progress: typeof import('vue-amazing-ui')['Progress']
    QRCode: typeof import('vue-amazing-ui')['QRCode']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('vue-amazing-ui')['Swiper']
    VanCircle: typeof import('vant/es')['Circle']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
