/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CusData: typeof import('./src/components/CusData/index.vue')['default']
    CusEmpty: typeof import('./src/components/CusEmpty/index.vue')['default']
    CusInput: typeof import('./src/components/CusInput/index.vue')['default']
    CusLang: typeof import('./src/components/CusLang/index.vue')['default']
    CusList: typeof import('./src/components/CusList/index.vue')['default']
    CusNav: typeof import('./src/components/CusNav/index.vue')['default']
    CusQa: typeof import('./src/components/CusQa/index.vue')['default']
    QRCode: typeof import('vue-amazing-ui')['QRCode']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
  }
}
